### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by realyze** [kriskowal/q#244]
I'm using [node-sandboxed-module](https://github.com/felixge/node-sandboxed-module) to do DI for my unit tests. The tests are using Mocha.

Now, when I run the tests, I am getting the following warning:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.EventEmitter.addListener (events.js:168:15)
    at process.startup.processSignalHandlers.process.on.process.addListener (node.js:465:29)
    at /Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:665:13
    at /Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:44:26
    at Object.<anonymous> (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:63:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/realyze/code/salsita/trunk/src/Project-Evolution/lib/auth.js:1:71)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at requireLike (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/sandboxed-module/node_modules/require-like/lib/require-like.js:15:26)
    at requireInterceptor (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/sandboxed-module/lib/sandboxed_module.js:102:9)
    at Object.<anonymous> (/Users/realyze/code/salsita/trunk/src/Project-Evolution/routes/login.js:5:10)
    at SandboxedModule._compile (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/sandboxed-module/lib/sandboxed_module.js:122:34)
    at SandboxedModule._init (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/sandboxed-module/lib/sandboxed_module.js:56:8)
    at Function.SandboxedModule.load (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/sandboxed-module/lib/sandboxed_module.js:24:19)
    at Function.SandboxedModule.require (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/sandboxed-module/lib/sandboxed_module.js:31:15)
    at request.post.send.userName (/Users/realyze/code/salsita/trunk/src/Project-Evolution/tests/unit/login_spec.js:77:29)
    at _fulfilled (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:837:54)
    at resolvedValue.promiseDispatch.done (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:867:30)
    at makePromise.promise.promiseDispatch (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:519:13)
    at pending (/Users/realyze/code/salsita/trunk/src/Project-Evolution/node_modules/q/q.js:422:39)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

It's fairly easy to get rid of it by bumping maxListeners limit. However, I'm not setting any emitters in my code (it's a fairly simple server) so I don't see why I should be getting that. It looks like it might be coming from Q though.

**Comment by hktalent** [comment]
(node:22855) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 option:proxy listeners added. Use emitter.setMaxListeners() to increase limit
