### ISSUE TITLE
Type error when chaining Q.ninvoke 

### ISSUE THREAD

**Issue by jasson15** [kriskowal/q#691]
There is an error when I was trying to use Q to chain `mongodb` functions as follow:
``` javascript
Q.ninvoke(MongoClient, 'connect', 'mongodb://127.0.0.1:27017/mydb')
.then(function(db){
    return Q
    .ninvoke(db, 'createCollection', 'mycollection')
    .ninvoke(db.collection('mycollection'), 'createIndex', {id: 1}) // error occurs here
    .ninvoke(db, 'close')
    .then(function(){...})
});
```
The error message I got:
``` javascript
    TypeError: Cannot call method 'apply' of undefined
      at Promise.post (/path/to/my/project/node_modules/q/q.js:1157:36)
      at Promise.promise.promiseDispatch (/path/to/my/project/node_modules/q/q.js:784:41)
      at /path/to/my/project/node_modules/q/q.js:600:44
      at runSingle (/path/to/my/project/node_modules/q/q.js:133:13)
      at flush (/path/to/my/project/node_modules/q/q.js:121:13)
      at process._tickCallback (node.js:442:13)
```
If I change the code like this, everything works fine again:
``` javascript
Q.ninvoke(MongoClient, 'connect', 'mongodb://127.0.0.1:27017/mydb')
.then(function(db){
    return Q
    .ninvoke(db, 'createCollection', 'mycollection')
    .then(function(){
        return Q.ninvoke(db.collection('mycollection'), 'createIndex', {id: 1}) // no error this time
        .then(function(){
             return Q.ninvoke(db, 'close').then(function(){...});
        });
    });
});
```
However, here comes a pyramid which grows along with the chain. I think Q should have supported chaining `ninvoke` like the first example, but it fails here:

``` javascript
Q.fulfill = fulfill;
function fulfill(value) {
    return Promise({
    ...
    // q.js line 1151
    "post": function (name, args) {
        if (name === null || name === void 0) {
            return value.apply(void 0, args);
        } else {
            return value[name].apply(value, args); // error occurs here: line 1157
        }
}
```
Although I have little idea what's going on inside the Q, I guess `db.collection('mycollection')` is not passed correctly as `value` in line 1157.

Versions I used:
Q: 1.4.0
node.js: v0.10.36

**Comment by jasson15** [comment]
I rule out the factor of MongoDB and narrow down the scope of the problem as follow:
``` javascript
    var TestClass = function (name){
    };

    TestClass.prototype.printName = function (callback) {
    	console.log('printName called');
    	return callback(null);
    };

    var test = new TestClass('test object');

    test.printName(function (err) {
		test.printName(function (err) {
			console.log('callback called');
		});
	});
```

In this case, the output should be:
```
    $ node q-test.js
    printName called
    printName called
    callback called
```
But if I use Q as follow:
``` javascript
    Q.ninvoke(test, 'printName')
    .ninvoke(test, 'printName')
    .then(function(){
    	console.log('callback called');
    })
    .done();
```
It turns out the output with an error like this:
``` javascript
    $ node test.js
    printName called

    /path/to/my/project/node_modules/q/q.js:155
                    throw e;
                          ^
    TypeError: Cannot read property '[object Object]' of undefined
        at Promise.post (/path/to/my/project/node_modules/q/q.js:1161:29)
        at Promise.promise.promiseDispatch (/path/to/my/project/node_modules/q/q.js:788:41)
        at /path/to/my/project/node_modules/q/q.js:556:49
        at runSingle (/path/to/my/project/node_modules/q/q.js:137:13)
        at flush (/path/to/my/project/node_modules/q/q.js:125:13)
        at process._tickCallback (node.js:442:13)
        at Function.Module.runMain (module.js:499:11)
        at startup (node.js:119:16)
        at node.js:929:3
```

**Comment by jasson15** [comment]
I found that's my fault -- I use `ninvoke` in a wrong way.
Here is the correct use provided by @barry-johnson
``` javascript
var TestClass = function (name){ };

TestClass.prototype.printName = function (callback) {
    console.log('printName called');
    return callback(null,this);     // node style callback, also return this
};

var test = new TestClass('test object');

Q.ninvoke(test, 'printName')
//  in the lines below, the result of the prior line is the "implied" first
// parameter to ninvoke();
.ninvoke('printName')
.ninvoke('printName')   
.then(function(){
    console.log('callback called');
})
.done();
```
Please see the discussion for more detail:
[discussion on stackoverflow](http://stackoverflow.com/questions/30181026/type-error-when-chaining-q-ninvoke)
