### ISSUE TITLE
Trouble with chained promises

### ISSUE THREAD

**Issue by AliUz** [kriskowal/q#699]
I am using Express and in one of my get routes I have a promise structure, which basically builds an object and finally returns it to the user via res.send. 
At high loads (thousands of requests per second), I start to see exceptions being thrown in my application. Here is how my application is structured:

```javascript
            app.get('/endpoint', function (req, res) {
            validator.validate(req.query, {
                // check query to see if valid
            }).then(function (valResult) {
               // if result passes validation get application id from database
            }).then(function (app) {
            // do a bunch of IO operations to build resulting object
            })
            //processObj functions return deferred.promises 
            .then(function(obj1){ return processObj1(obj1); }) 
            .then(function(obj2){ return processObj2(obj2); })
            .then(function(obj3){ return processObj3(obj3); })
            }).then(function (result) {
                if (result.platform === 'mobile') {
                    res.jsonp({code: 100, message: 'SUCCESS', data: result});
                }
                else {
                    res.send({code: 100, message: 'SUCCESS', data: result});
                }
            }).fail(function (error) {
                if (error.stack) {
                    console.log(error.message);
                    console.log(error.stack);
                    res.send({code: 500, message: 'FAIL_SYSTEM', data: error.message});
                } else {
                    res.send(error);
                }
            });
        }
```

I am getting an Error saying that the application cannot set headers after they are sent which is an Express error telling me that I have already issued a res.send so I can't issue it again. 
Is it possible that this error occurs because my promises are not executing in order? I tried to debug the application and saw that the middle "then"s execute after the final "then", is this even possible using promises? Or could it be that one of the promises is returning more than one promise to the next function in the chain? 

Here is the full error (using q@0.9.7):

``` javascript
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.res.setHeader (/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/node_modules/express/lib/response.js:522:10)
    at ServerResponse.res.jsonp (/node_modules/express/lib/response.js:236:8)
    at <path-to-module>/module.js:157:29
    at _fulfilled (/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/node_modules/q/q.js:760:13)
    at /node_modules/q/q.js:574:44
    at flush (/node_modules/q/q.js:108:17)
```

**Comment by AliUz** [comment]
Upon further investigation I've noticed that I get the same errors even with a smaller promise chain, for example something along the lines of:

```javascript
           app.get('/endpoint', function (req, res) {
             validator.validate(req.query, {
                // check query to see if valid
             }).then(function (query) {
               // query database for app
             }).then(function (app) {
               if (app) {
                  res.send({code: 100, message: 'SUCCESS', message: "hooray app found!"});
             }).fail(function(err) {
                  res.send("Fail :(");
             });
```

With Jmeter, if I send 2000 threads with a loop count of 10, the errors will start piling up. (Can't set headers after they are sent following a bunch of timeouts).

**Comment by AliUz** [comment]
Nevermind, my issue has nothing to do with the promise structure, the error is a result of express timing out then the promise trying to resolve and attempting to do a res.send after the timeout response causing this error.
