### ISSUE TITLE
v1.4.1- Cannot call method 'push' of undefined@/q.js:552:35

### ISSUE THREAD

**Issue by AndrewHuffman** [kriskowal/q#707]
We've started getting these exceptions. We started noticing them after we updated to v1.4.1, but it's uncertain if that's why we started seeing this.

The stack trace looks like this:
```* [
    "TypeError: Cannot call method 'push' of undefined",
    "    at Promise.promise.promiseDispatch (/home/vcap/app/node_modules/q/q.js:552:35)",
    "    at Promise.then (/home/vcap/app/node_modules/q/q.js:875:10)",
    "    at Promise.done (/home/vcap/app/node_modules/q/q.js:1801:13)",
    "    at RealTimeClient.<anonymous> (/home/vcap/app/src/lib/src/util/realtime.js:603:18)",
    "    at try_callback (/home/vcap/app/node_modules/redis/index.js:592:9)",
    "    at RedisClient.return_reply (/home/vcap/app/node_modules/redis/index.js:685:13)",
    "    at ReplyParser.<anonymous> (/home/vcap/app/node_modules/redis/index.js:321:14)",
    "    at ReplyParser.emit (events.js:95:17)",
    "    at ReplyParser.send_reply (/home/vcap/app/node_modules/redis/lib/parser/javascript.js:300:10)",
    "    at ReplyParser.execute (/home/vcap/app/node_modules/redis/lib/parser/javascript.js:203:22)",
    "    at RedisClient.on_data (/home/vcap/app/node_modules/redis/index.js:547:27)",
    "    at Socket.<anonymous> (/home/vcap/app/node_modules/redis/index.js:102:14)",
    "    at Socket.emit (events.js:95:17)",
    "    at Socket.<anonymous> (_stream_readable.js:765:14)",
    "    at Socket.emit (events.js:92:17)",
    "    at emitReadable_ (_stream_readable.js:427:10)",
    "    at emitReadable (_stream_readable.js:423:5)",
    "    at readableAddChunk (_stream_readable.js:166:9)",
    "    at Socket.Readable.push (_stream_readable.js:128:10)",
    "    at TCP.onread (net.js:529:21)"
]```

Our code that originates the issue is within a callback from a client. I can't provide our exact code, but it looks something like this:

```
    MyObject.prototype.getDocument = function (key) {
        var deferred = Q.defer();
        this.client.get(key, function (err, reply) {
            if (err) {
                deferred.reject(err);
            } else if (reply) {
                this.doSomethingElse(reply)
                .then(function(success){
                    deferred.resolve(success);
                }, function(failure){
                    deferred.reject(failure);
                }).done();
            } else {
                deferred.reject(new Error('No reply'));
            }
       }.bind(this));
       return deferred.promise;
    }
```

The exception comes from the `.done()` call in the secondary call. Looking at the stack trace, it appears that within q.js the `progressListeners` is become `undefined`. `progressListeners` is voided out when `become` is called. I'm wondering if there's a race condition here. If our client callback gets called twice in a row then we call resolve or reject on the deferred.


```
    function become(newPromise) {
        resolvedPromise = newPromise;
        promise.source = newPromise;

        array_reduce(messages, function (undefined, message) {
            Q.nextTick(function () {
                newPromise.promiseDispatch.apply(newPromise, message);
            });
        }, void 0);

        messages = void 0;
        progressListeners = void 0;
    }

    deferred.promise = promise;
    deferred.resolve = function (value) {
        if (resolvedPromise) {
            return;
        }

        become(Q(value));
    };
```

So, if `deferred.resolve` is called twice in a row on separate threads, and both threads make it past the `if` block, then it would appear this could happen. Also, if the promises' `.then` is called after the `become()` call this could also happen.

Obviously I could be looking at this wrong, or we're doing something wrong. 

Please advice.

**Comment by AndrewHuffman** [comment]
Has anyone had a chance to look at this?

**Comment by kriskowal** [comment]
I have not had a moment to spare.

Please clarify what engine (Node.js?) you are using so we can dismiss the possibility that you are using actual threads. I presume you’re using "thread" figuratively. If you are using "thread" literally, all bets are off.

Note that you can do `deferred.resolve(this.doSomethingElse())` instead of hooking up the resolve/reject through then.

This might be something simple to isolate with a test case. I’m ready to believe that progress listener code is undertested. It has been eliminated in v2.
