### ISSUE TITLE
Q 2.0.0 "Cannot find module 'collections/shim'"

### ISSUE THREAD

**Issue by cariseterravion** [kriskowal/q#713]
Just started seeing this issue when I do a clean installation of my app (which is using Q 2.0.0):

```
module.js:340

    throw err;
          ^
Error: Cannot find module 'collections/shim'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/scratch/overview/api/node_modules/q/q.js:43:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

My package.json has q in the dependencies section:

...
"q": "2.0.0"
...

And when I did npm install, I had no errors.

**Comment by kriskowal** [comment]
Thanks. Sorry for the instability. I recently published a version of Collections that does not support shims. Q needs an update.

**Comment by kriskowal** [comment]
Oh, problem is that you’ve pinned to the 2.0.0 exact version. This problem does not exist in version 2.0.3 since the collections dependency has been removed.

**Comment by cariseterravion** [comment]
Thanks for the quick reply! I'll relax the version and try it.

**Comment by AStoker** [comment]
There is no more a 2.0.3 release. There's some confusion at this point about which release to go for (a 2.0 release, or a newer 1.5 release).

**Comment by kriskowal** [comment]
It’s fair to say at this point that Q@^1 is Q forever. A version 2 has turned out to not be practical.

**Comment by AStoker** [comment]
👍 Thanks for the clarification.
