### ISSUE TITLE
Hey all my libs are broken because Q use collectoins/shim

### ISSUE THREAD

**Issue by DrMabuse23** [kriskowal/q#714]
error: 
`````
module.js:338
    throw err;
    ^
Error: Cannot find module 'collections/shim'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pascalbrewing/htdocs/cli/mcap-deploy/node_modules/q/q.js:43:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
``````
becuase collections 2.02. removed the shim it woul be nice a quickly fix

**Comment by kriskowal** [comment]
check your version of Q. latest patch of 2 does not depend on collections.

**Comment by DrMabuse23** [comment]
Fixed thx
